kill shims, they're irrelevant, this issue repros in chrome as well as phantomjs.
trying to track down root cause of
Warning: Error unmounting:
Error: Invariant Violation: unmountComponentAtNode(...): Target
container is not a DOM element.